# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: آموزش کار با گیت
email: as.aminirobati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  من اشرف سادات امینی رباطی هستم و در دانشگاه بزرگمهر قاینات هستم وتصمیم دارم دراین سایت به شمادوستان عزیز کار با گیت را آموزش دهم.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://A-Amini.ir" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Ashraf-Amini.github.io

# Build settings
markdown: kramdown
